spring:
    application:
        name: LhtFs

    servlet:
        multipart:
            max-file-size: 10MB


lhtfs:
    path: F:\lhtfs8080
    syncBackup: false #同步备份还是异步备份
    autoMd5: true
    group: L8090
    backupUrl: http://localhost:8091/upload
    downloadUrl: http://localhost:8090/download


rocketmq:
    name-server: localhost:9876
    producer:
        group: lhtfs-producer

server:
    port: 8090