spring:
    application:
        name: LhtFs

    servlet:
        multipart:
            max-file-size: 10MB


lhtfs:
    path: F:\lhtfs8080
    autoMd5: true
    backupUrl: http://localhost:8081/upload